#!/usr/bin/env python3

import argparse
import subprocess
import re
import shutil
import base64
import binascii
import hashlib
import tempfile
import os
import math
import urllib.parse
import codecs
import zipfile
from pathlib import Path
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.prompt import Confirm
from rich.progress import Progress, SpinnerColumn, BarColumn, TextColumn, TimeElapsedColumn
from rich import box

# Files generated by tools themselves — NOT steganographic content.
# Recursing into these causes infinite loops (e.g. foremost rewrites
# audit.txt with new timestamps each run, so SHA-256 never matches).
_TOOL_ARTIFACTS = {'audit.txt', 'report.txt', 'foremost.log'}

# Extensions that should only receive a lightweight text scan during
# recursion (no binwalk / foremost / steghide on plain-text files).
_TEXT_EXTENSIONS = {
    '.txt', '.log', '.md', '.csv', '.json', '.xml',
    '.html', '.htm', '.cfg', '.ini', '.conf', '.py', '.sh',
}

# Hard cap on recursion depth. Values above this are clamped and warned.
# Rationale: each depth level adds ~15-20 Python frames (CTFuck.__init__,
# scan, run_binwalk, _analyze_file …). At depth 50 we're already well
# inside the default CPython stack limit (1000 frames). Practically,
# legitimate nested-stego CTF challenges never need more than 5-6 levels.
_MAX_RECURSION_DEPTH_HARD_CAP = 10

# Zip-bomb guard: if the total uncompressed size of a ZIP exceeds this
# many times its compressed size we refuse to extract it.
_ZIP_BOMB_RATIO = 100          # 100x compression ratio threshold
_ZIP_BOMB_MAX_BYTES = 200 * 1024 * 1024  # never extract more than 200 MB total

DEFAULT_FLAG_FORMATS = [
    "STMCTF{", "SiberVatan{", "CTF{", "FLAG{", "flag{", "ctf{", "picoCTF{", "DUCTF{",
    "HTB{", "THM{", "CSAW{", "DarkCTF{", "RITSEC{", "TUCTF{", "nactf{",
    "zer0pts{", "BCACTF{", "DCTF{", "wectf{", "zh3r0{", "justCTF{",
    "X-MAS{", "cybrics{", "SquareCTF{", "WPICTF{", "BYUCTF{"
]

console = Console()

BANNER = "CTFuck - Steganography Automation Tool"

# ---------------------------------------------------------------------------
# Default embedded wordlist (~150 most common CTF/stego passwords)
# ---------------------------------------------------------------------------
DEFAULT_WORDLIST = [
    # Empty / trivial
    '', 'password', 'Password', 'PASSWORD',
    # Numeric
    '123456', '12345678', '1234', '12345', '123456789', '000000', '111111',
    '654321', '666666', '1q2w3e4r', '1q2w3e', 'qwerty', 'qwerty123', 'qwertyuiop',
    # Common words
    'admin', 'Admin', 'root', 'user', 'test', 'guest', 'pass', 'pass123',
    'password1', 'password123', 'letmein', 'welcome', 'welcome1',
    'monkey', 'dragon', 'master', 'sunshine', 'princess', 'iloveyou',
    'shadow', 'superman', 'batman', 'trustno1', 'football', 'baseball',
    'soccer', 'hockey', 'jordan', 'harley', 'ranger', 'dakota', 'cookie',
    'maggie', 'jessica', 'michael', 'charlie', 'thomas', 'hunter', 'pepper',
    'access', 'andrew', 'george', 'jordan23', 'robert', 'daniel', 'hello',
    'starwars', 'midnight', 'mustang', 'maverick', 'matrix', 'coffee',
    # CTF-specific
    'ctf', 'CTF', 'flag', 'Flag', 'FLAG',
    'ctf2024', 'ctf2025', 'ctf2023',
    'challenge', 'hackme', 'hacker', 'hackthebox', 'tryhackme',
    'picoctf', 'pwn', 'exploit', 'solve', 'answer',
    # Stego-specific
    'steg', 'stego', 'Stego', 'STEGO',
    'steghide', 'steganography', 'hidden', 'secret', 'Secret', 'SECRET',
    'embed', 'embedded', 'invisible', 'conceal', 'covert', 'hide',
    # Crypto-related
    'key', 'Key', 'KEY', 'mykey', 'publickey', 'privatekey',
    'crypto', 'cipher', 'encode', 'decode', 'encrypt', 'decrypt',
    'base64', 'binary', 'hex', 'ascii',
    # Common short passwords
    'abc', 'abc123', 'pass1', 'p@ss', 'p@ssw0rd', 'p@$$w0rd',
    'sup3r', 's3cr3t', 's3cret', 'h1dd3n', '0wn3d',
    # Names & places often used
    'admin123', 'root123', 'toor', 'kali', 'parrot', 'ubuntu', 'debian', 'linux',
    # Seasonal / event
    'summer', 'winter', 'spring', 'autumn', 'christmas', 'newyear',
]


class ToolChecker:
    REQUIRED_TOOLS = {
        'strings': 'binutils',
        'zsteg': 'zsteg (gem install zsteg)',
        'exiftool': 'libimage-exiftool-perl',
        'binwalk': 'binwalk',
        'steghide': 'steghide',
        'outguess': 'outguess',
        'foremost': 'foremost'
    }

    @staticmethod
    def check_tool(tool_name):
        return shutil.which(tool_name) is not None

    @classmethod
    def check_all_tools(cls):
        status = {}
        for tool, package in cls.REQUIRED_TOOLS.items():
            status[tool] = cls.check_tool(tool)
        return status


class CTFuck:
    def __init__(self, file_path, flag_formats, wordlist=None, auto_brute=False,
                 max_recursion_depth=3, _depth=0, _visited=None, quiet=False):
        self.file_path = Path(file_path)
        if isinstance(flag_formats, str):
            self.flag_formats = [f.strip() for f in flag_formats.split(',') if f.strip()]
        else:
            self.flag_formats = [f.strip() for f in flag_formats]
        self.flag_patterns = self._build_flag_patterns(self.flag_formats)
        self.quiet = quiet
        self.found_flags = []
        self.interesting_strings = []
        self.suspicious_patterns = []
        self.metadata_findings = []
        self.tool_outputs = []           # [(tool_name, stdout, stderr), ...]
        self.tool_status = ToolChecker.check_all_tools()
        self.auto_brute = auto_brute
        self.wordlist = self._load_wordlist(wordlist)
        self._wordlist_path = wordlist   # keep raw path for sub-analyzers
        self._max_depth = max_recursion_depth
        self._depth = _depth             # current recursion depth

        # Shared visited set across all recursive instances (by SHA-256)
        self._visited = _visited if _visited is not None else set()

        if not self.file_path.exists():
            console.print(f"[bold red]✗ Error:[/bold red] File not found: {file_path}")
            exit(1)

        # Register self in visited set
        self._visited.add(self._file_hash(self.file_path))

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _file_hash(path):
        """Return SHA-256 hex digest for a file (for dedup)."""
        h = hashlib.sha256()
        try:
            with open(path, 'rb') as f:
                for chunk in iter(lambda: f.read(65536), b''):
                    h.update(chunk)
            return h.hexdigest()
        except Exception:
            return str(path)

    def _get_output_root(self):
        return self.file_path.parent / f"ctfuck_output_{self.file_path.stem}"

    def _persist_extracted_files(self, source_dir, tool_name):
        # Bug fix: sub-analyzers (depth > 0) operate inside temp directories
        # that are deleted after the call, so persisting is pointless and
        # produces paths like /tmp/tmpXXX/ctfuck_output_... that vanish.
        if self._depth > 0:
            return None

        source_path = Path(source_dir)
        if not source_path.exists():
            return None

        # Skip tool-generated artifacts (foremost audit.txt, etc.)
        extracted_files = [
            p for p in source_path.rglob('*')
            if p.is_file() and p.name.lower() not in _TOOL_ARTIFACTS
        ]
        if not extracted_files:
            return None

        output_root = self._get_output_root()
        destination_root = output_root / tool_name
        destination_root.mkdir(parents=True, exist_ok=True)

        for fp in extracted_files:
            relative_path = fp.relative_to(source_path)
            destination_path = destination_root / relative_path
            destination_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(fp, destination_path)

        return destination_root

    def _build_flag_patterns(self, flag_formats):
        patterns = []
        for fmt in flag_formats:
            escaped_prefix = re.escape(fmt)
            patterns.append(re.compile(rf"{escaped_prefix}[^\r\n\t ]{{0,300}}}}", re.IGNORECASE))
            patterns.append(re.compile(rf"{escaped_prefix}.{{0,300}}?}}", re.DOTALL | re.IGNORECASE))

            variations = {fmt, fmt.upper(), fmt.lower(), fmt.swapcase()}
            for variant in variations:
                if variant != fmt:
                    escaped_variant = re.escape(variant)
                    patterns.append(re.compile(rf"{escaped_variant}[^\r\n\t ]{{0,300}}}}", ))

            regex_like_tokens = (".*", ".+", "[", "(", "\\d", "\\w", "\\s", "|")
            if any(token in fmt for token in regex_like_tokens):
                try:
                    patterns.append(re.compile(fmt, re.IGNORECASE))
                except re.error:
                    pass

        return patterns

    def _load_wordlist(self, wordlist_path):
        """Load wordlist from file or use default common passwords."""
        if wordlist_path:
            try:
                with open(wordlist_path, 'r', encoding='utf-8', errors='ignore') as f:
                    passwords = [line.strip() for line in f if line.strip()]
                if self._depth == 0:
                    console.print(f"[green]✓ Loaded {len(passwords)} passwords from wordlist[/green]")
                return passwords
            except Exception as e:
                if self._depth == 0:
                    console.print(f"[yellow]⚠ Could not load wordlist: {e}. Using default passwords.[/yellow]")
                return DEFAULT_WORDLIST

        return DEFAULT_WORDLIST

    # ------------------------------------------------------------------
    # Recursive file analysis
    # ------------------------------------------------------------------

    def _analyze_file(self, file_path, depth=None):
        """
        Recursively analyze an extracted file with all available tools.
        Returns (flags, interesting_strings) lists.

        Defenses:
        1. Skip tool-generated artifact files (foremost audit.txt, etc.)
        2. For plain-text files, perform a lightweight content scan only.
        3. RecursionError is caught so a corrupt/adversarial deeply-nested
           archive cannot crash the entire process.
        """
        if depth is None:
            depth = self._depth + 1

        if depth > self._max_depth:
            return [], []

        fp = Path(file_path)
        if not fp.exists() or fp.stat().st_size == 0:
            return [], []

        # Skip tool-generated files that are never steganographic content
        if fp.name.lower() in _TOOL_ARTIFACTS:
            return [], []

        # Deduplication via SHA-256
        fhash = self._file_hash(fp)
        if fhash in self._visited:
            return [], []
        self._visited.add(fhash)

        indent = "  " * depth
        ext = fp.suffix.lower()

        # ── Lightweight path for plain-text files ──────────────────────────
        if ext in _TEXT_EXTENSIONS:
            flags = []
            interesting = []
            try:
                content = fp.read_text(errors='ignore')
                if content.strip():
                    console.print(
                        f"[dim]{indent}↳ Text scan: [bold]{fp.name}[/bold] (depth {depth})[/dim]"
                    )
                    flags = self.search_flags(content, f"text/{fp.name}")
                    encoded_flags, enc_interesting = self.find_encoded_flags(
                        content, f"text/{fp.name}"
                    )
                    flags.extend(encoded_flags)
                    interesting.extend(enc_interesting)
            except Exception:
                pass
            return flags, interesting

        # ── Full recursive analysis for binary / image / archive files ─────
        console.print(f"[dim]{indent}↳ Recursing into: [bold]{fp.name}[/bold] (depth {depth})[/dim]")

        try:
            sub = CTFuck(
                file_path=str(fp),
                flag_formats=self.flag_formats,
                wordlist=self._wordlist_path,
                auto_brute=self.auto_brute,
                max_recursion_depth=self._max_depth,
                _depth=depth,
                _visited=self._visited,
                quiet=self.quiet
            )
            sub.scan()
            return sub.found_flags, sub.interesting_strings
        except RecursionError:
            console.print(
                f"[yellow]  ⚠ Recursion limit hit analysing {fp.name} — skipping deeper layers[/yellow]"
            )
            return [], []
        except Exception:
            return [], []

    # ------------------------------------------------------------------
    # Banner / status
    # ------------------------------------------------------------------

    def show_banner(self):
        console.print(f"\n[bold cyan]{BANNER}[/bold cyan]")
        brute_tag = " | [bold yellow]auto-brute ON[/bold yellow]" if self.auto_brute else ""
        fmt_str = ", ".join(self.flag_formats) if len(self.flag_formats) < 4 else f"{len(self.flag_formats)} common formats"
        console.print(
            f"[dim]Target:[/dim] {self.file_path} | "
            f"[dim]Flags:[/dim] {fmt_str}"
            f"{brute_tag}\n"
        )

    def show_tool_status(self):
        available = [tool for tool, status in self.tool_status.items() if status]
        missing   = [tool for tool, status in self.tool_status.items() if not status]

        if available:
            console.print(f"[dim]Tools:[/dim] [green]{', '.join(available)}[/green]")
        if missing:
            console.print(f"[dim]Missing:[/dim] [red]{', '.join(missing)}[/red]")
        console.print()

    # ------------------------------------------------------------------
    # Command runner
    # ------------------------------------------------------------------

    def run_command(self, cmd, description, shell=False, silent=False, save_output=False):
        try:
            if not silent:
                console.print(f"[dim]→ {description}[/dim]")
            result = subprocess.run(
                cmd,
                shell=shell,
                capture_output=True,
                text=True,
                errors='ignore',
                timeout=60
            )
            if save_output:
                self.tool_outputs.append((description, result.stdout, result.stderr))
            return result.stdout, result.stderr, result.returncode
        except subprocess.TimeoutExpired:
            if not silent:
                console.print(f"[red]✗ Timeout: {description}[/red]")
            return "", "Timeout", -1
        except Exception as e:
            if not silent:
                console.print(f"[red]✗ Error: {str(e)}[/red]")
            return "", str(e), -1

    # ------------------------------------------------------------------
    # Flag search
    # ------------------------------------------------------------------

    def search_flags(self, text, source="unknown"):
        found = []
        for pattern in self.flag_patterns:
            for match in pattern.findall(text):
                if isinstance(match, tuple):
                    match = "".join(match)
                cleaned = re.sub(r"[\r\n\t]+", "", match).strip()
                if cleaned:
                    found.append((cleaned, source))
        return found

    def calculate_entropy(self, data: bytes):
        if not data:
            return 0
        byte_counts = [0] * 256
        for byte in data:
            byte_counts[byte] += 1
        entropy = 0
        data_len = len(data)
        for count in byte_counts:
            if count > 0:
                p_x = count / data_len
                entropy += -p_x * math.log(p_x, 2)
        return entropy

    def find_encoded_flags(self, text, source="unknown"):
        found = []
        interesting = []

        # 1. Base64
        b64_patterns = [
            re.compile(r'(?:[A-Za-z0-9+/]{4}){4,}(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?'),
            re.compile(r'(?:[A-Za-z0-9+/]{4}){2,}(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)')
        ]
        for pattern in b64_patterns:
            for b64_match in pattern.findall(text):
                if len(b64_match) < 8:
                    continue
                try:
                    decoded = base64.b64decode(b64_match).decode('utf-8', errors='ignore')
                    if decoded.strip():
                        flags = self.search_flags(decoded, source)
                        if flags:
                            found.extend(flags)
                        recursive_flags, recursive_interesting = self.find_encoded_flags(decoded, source)
                        found.extend(recursive_flags)
                        interesting.extend(recursive_interesting)
                        self._check_interesting_content(decoded, f"[Base64] {b64_match[:50]}...", source, interesting)
                except Exception:
                    pass

        # 2. Hex
        hex_patterns = [
            re.compile(r'\b(?:[0-9a-fA-F]{2}){8,}\b'),
            re.compile(r'(?:0x[0-9a-fA-F]{2}\s*){4,}'),
            re.compile(r'(?:[0-9a-fA-F]{2}\s+){4,}')
        ]
        for pattern in hex_patterns:
            for hex_match in pattern.findall(text):
                cleaned_hex = re.sub(r'[^0-9a-fA-F]', '', hex_match)
                if len(cleaned_hex) < 8 or len(cleaned_hex) % 2 != 0:
                    continue
                try:
                    decoded = binascii.unhexlify(cleaned_hex).decode('utf-8', errors='ignore')
                    if decoded.strip():
                        flags = self.search_flags(decoded, source)
                        if flags:
                            found.extend(flags)
                        self._check_interesting_content(decoded, f"[Hex] {hex_match[:50]}...", source, interesting)
                except Exception:
                    pass

        # 3. URL encoding
        url_pattern = re.compile(r'(?:%[0-9a-fA-F]{2}){3,}')
        for url_match in url_pattern.findall(text):
            try:
                decoded = urllib.parse.unquote(url_match)
                if decoded != url_match and decoded.strip():
                    flags = self.search_flags(decoded, source)
                    if flags:
                        found.extend(flags)
                    self._check_interesting_content(decoded, f"[URL] {url_match[:50]}...", source, interesting)
            except Exception:
                pass

        # 4. ROT13
        try:
            rot13_decoded = codecs.decode(text, 'rot_13')
            if rot13_decoded != text:
                flags = self.search_flags(rot13_decoded, source)
                for flag in flags:
                    found.append((flag[0], f"{source} (ROT13)"))
        except Exception:
            pass

        # 5. Binary
        binary_pattern = re.compile(r'\b[01]{8,}\b')
        for binary_match in binary_pattern.findall(text):
            if len(binary_match) % 8 != 0:
                continue
            try:
                decoded = ''.join(chr(int(binary_match[i:i+8], 2)) for i in range(0, len(binary_match), 8))
                if decoded.strip():
                    flags = self.search_flags(decoded, source)
                    if flags:
                        found.extend(flags)
                    self._check_interesting_content(decoded, f"[Binary] {binary_match[:50]}...", source, interesting)
            except Exception:
                pass

        # 6. Octal
        octal_pattern = re.compile(r'(?:\\[0-7]{3}){3,}')
        for octal_match in octal_pattern.findall(text):
            try:
                decoded = codecs.decode(octal_match, 'unicode_escape')
                if decoded.strip():
                    flags = self.search_flags(decoded, source)
                    if flags:
                        found.extend(flags)
                    self._check_interesting_content(decoded, f"[Octal] {octal_match[:50]}...", source, interesting)
            except Exception:
                pass

        # 7. ASCII decimal
        ascii_pattern = re.compile(r'\b(?:\d{2,3}[,\s]+){4,}\d{2,3}\b')
        for ascii_match in ascii_pattern.findall(text):
            try:
                numbers = re.findall(r'\d+', ascii_match)
                decoded = ''.join(chr(int(n)) for n in numbers if 0 <= int(n) <= 127)
                if decoded.strip() and len(decoded) > 3:
                    flags = self.search_flags(decoded, source)
                    if flags:
                        found.extend(flags)
                    self._check_interesting_content(decoded, f"[ASCII] {ascii_match[:50]}...", source, interesting)
            except Exception:
                pass

        # 8. Base32
        base32_pattern = re.compile(r'\b[A-Z2-7]{8,}={0,6}\b')
        for b32_match in base32_pattern.findall(text):
            if len(b32_match) < 8:
                continue
            try:
                decoded = base64.b32decode(b32_match).decode('utf-8', errors='ignore')
                if decoded.strip():
                    flags = self.search_flags(decoded, source)
                    if flags:
                        found.extend(flags)
                    self._check_interesting_content(decoded, f"[Base32] {b32_match[:50]}...", source, interesting)
            except Exception:
                pass

        # 9. Reversed
        reversed_text = text[::-1]
        reversed_flags = self.search_flags(reversed_text, source)
        for flag in reversed_flags:
            found.append((flag[0], f"{source} (Reversed)"))

        return found, interesting

    def _check_interesting_content(self, decoded, encoding_info, source, interesting_list):
        """Enhanced interesting content detection."""
        if not decoded or len(decoded) < 3:
            return
        decoded_lower = decoded.lower()
        is_printable = all(32 <= ord(c) < 127 or c in '\n\r\t' for c in decoded)
        if not is_printable:
            return

        ctf_keywords = ['flag', 'ctf', 'challenge', 'solve', 'answer']
        if any(kw in decoded_lower for kw in ctf_keywords):
            interesting_list.append((f"{encoding_info} -> {decoded[:150]}", f"{source} [CTF Keyword]"))
            return

        secret_keywords = ['password', 'passwd', 'pwd', 'secret', 'key', 'token', 'api', 'auth']
        if any(kw in decoded_lower for kw in secret_keywords):
            interesting_list.append((f"{encoding_info} -> {decoded[:150]}", f"{source} [Credentials]"))
            return

        admin_keywords = ['admin', 'root', 'user', 'login', 'username']
        if any(kw in decoded_lower for kw in admin_keywords):
            interesting_list.append((f"{encoding_info} -> {decoded[:150]}", f"{source} [Access Info]"))
            return

        if any(p in decoded_lower for p in ['http://', 'https://', 'ftp://', '://']):
            interesting_list.append((f"{encoding_info} -> {decoded[:150]}", f"{source} [URL]"))
            return

        if decoded.startswith('/') or ':\\\\' in decoded or re.search(r'[A-Z]:\\\\', decoded):
            interesting_list.append((f"{encoding_info} -> {decoded[:150]}", f"{source} [File Path]"))
            return

        code_patterns = ['import ', 'function ', 'def ', 'class ', 'echo ', 'cat ', 'ls ', 'grep ']
        if any(pattern in decoded_lower for pattern in code_patterns):
            interesting_list.append((f"{encoding_info} -> {decoded[:150]}", f"{source} [Code/Command]"))
            return

        if len(decoded) > 20 and decoded.count(' ') > 2:
            words = decoded.split()
            if len(words) > 3:
                interesting_list.append((f"{encoding_info} -> {decoded[:150]}", f"{source} [Long Text]"))

    def _detect_suspicious_patterns(self, text, source):
        repeated_pattern = re.compile(r'(\b\w{4,}\b)(?:\s+\1){2,}')
        for match in repeated_pattern.finditer(text):
            self.suspicious_patterns.append((f"Repeated word: '{match.group(1)}'", source))

        if len(text) > 100:
            char_freq = {}
            for char in text:
                if char.isalnum():
                    char_freq[char] = char_freq.get(char, 0) + 1
            total_alnum = sum(char_freq.values())
            if total_alnum > 0:
                for char, count in char_freq.items():
                    if count / total_alnum > 0.3:
                        self.suspicious_patterns.append(
                            (f"High frequency character: '{char}' ({count/total_alnum*100:.1f}%)", source)
                        )
                        break

        stego_markers = ['BEGIN', 'END', 'HIDDEN', 'EMBEDDED', 'STEALTH', 'COVERT']
        for marker in stego_markers:
            if marker in text.upper():
                ctx_start = max(0, text.upper().find(marker) - 20)
                ctx_end   = min(len(text), text.upper().find(marker) + len(marker) + 20)
                context   = text[ctx_start:ctx_end]
                self.suspicious_patterns.append((f"Steganography marker '{marker}': {context}", source))

    def _scan_extracted_files(self, extract_dir, tool_name, max_depth=3, current_depth=0):
        """Light scan of extracted files (strings + content). Deep analysis via _analyze_file."""
        flags_found = []
        has_strings = self.tool_status.get('strings', False)

        if current_depth >= max_depth:
            return flags_found

        for root, dirs, files in os.walk(extract_dir):
            for file in files:
                # Skip tool-generated artifacts (foremost audit.txt, etc.)
                if file.lower() in _TOOL_ARTIFACTS:
                    continue

                file_path = os.path.join(root, file)
                file_source = f"{tool_name} -> {os.path.relpath(file_path, extract_dir)}"

                try:
                    file_size = os.path.getsize(file_path)
                    if file_size == 0:
                        continue
                    if file_size > 50 * 1024 * 1024:
                        continue

                    with open(file_path, 'rb') as f:
                        raw_data = f.read()

                    # Strings scan
                    if has_strings:
                        try:
                            stdout, stderr, code = self.run_command(
                                ['strings', file_path],
                                f"Scanning: {os.path.basename(file_path)}"
                            )
                            flags = self.search_flags_from_outputs(stdout, stderr, file_source)
                            if flags:
                                flags_found.extend(flags)
                        except Exception:
                            pass

                    # Direct content scan
                    try:
                        content = raw_data.decode('utf-8', errors='ignore')
                        if content.strip():
                            flags = self.search_flags(content, file_source)
                            if flags:
                                flags_found.extend(flags)
                            encoded_flags, interesting = self.find_encoded_flags(content, file_source)
                            if encoded_flags:
                                flags_found.extend(encoded_flags)
                            if interesting:
                                self.interesting_strings.extend(interesting)
                    except Exception:
                        pass

                except Exception:
                    pass

        return flags_found

    def _extract_metadata_info(self, metadata_output, source):
        interesting_fields = [
            'comment', 'description', 'author', 'creator', 'software',
            'user comment', 'artist', 'copyright', 'keywords', 'subject'
        ]
        for line in metadata_output.split('\n'):
            line_lower = line.lower()
            for field in interesting_fields:
                if field in line_lower and ':' in line:
                    parts = line.split(':', 1)
                    if len(parts) == 2:
                        value = parts[1].strip()
                        if value and len(value) > 3:
                            self.metadata_findings.append((f"{parts[0].strip()}: {value}", source))

    def search_flags_from_outputs(self, stdout, stderr, source="unknown"):
        combined = f"{stdout}\n{stderr}"
        flags = self.search_flags(combined, source)
        encoded_flags, interesting = self.find_encoded_flags(combined, source)
        flags.extend(encoded_flags)
        if interesting:
            self.interesting_strings.extend(interesting)
        return flags

    # ------------------------------------------------------------------
    # Tool runners
    # ------------------------------------------------------------------
    def scan(self):
        if self._depth == 0:
            console.print("\n[bold cyan]🔍 Scanning...[/bold cyan]")

        # 1. Fast Tools
        self.run_strings()
        self.run_exiftool()
        self.run_zsteg()
        
        last_flag_count = len(self.found_flags)
        if last_flag_count > 0 and self._depth == 0:
            self.show_results()
            if not Confirm.ask("\n[bold yellow]Flags found! Do you want to continue with Extraction (Binwalk/Foremost)?[/bold yellow]", default=False):
                import sys
                sys.exit(0)

        # 2. Extraction & Recursion Tools
        self.run_binwalk()
        self.run_foremost()
        
        if len(self.found_flags) > last_flag_count and self._depth == 0:
            last_flag_count = len(self.found_flags)
            self.show_results()
            if not Confirm.ask("\n[bold yellow]New flags found through extraction! Do you want to continue with Password Brute-Force (Steghide/Outguess/Zip)?[/bold yellow]", default=False):
                import sys
                sys.exit(0)

        # 3. Brute Force Tools
        self.run_steghide()
        self.run_outguess()
        self.bruteforce_archives()

    def run_strings(self):
        if not self.tool_status['strings']:
            return
        stdout, stderr, code = self.run_command(
            ['strings', str(self.file_path)],
            "strings",
            save_output=True
        )
        flags = self.search_flags_from_outputs(stdout, stderr, "strings")
        if flags:
            console.print(f"[green]✓ strings: {len(flags)} flag(s)[/green]")
            self.found_flags.extend(flags)

    def run_zsteg(self):
        if not self.tool_status['zsteg']:
            return
        if self.file_path.suffix.lower() not in ['.png', '.bmp']:
            return
        stdout, stderr, code = self.run_command(
            ['zsteg', '-a', str(self.file_path)],
            "zsteg",
            save_output=True
        )
        flags = self.search_flags_from_outputs(stdout, stderr, "zsteg")
        if flags:
            console.print(f"[green]✓ zsteg: {len(flags)} flag(s)[/green]")
            self.found_flags.extend(flags)

    def run_exiftool(self):
        if not self.tool_status['exiftool']:
            return
        stdout, stderr, code = self.run_command(
            ['exiftool', str(self.file_path)],
            "exiftool",
            save_output=True
        )
        if code == 0:
            flags = self.search_flags_from_outputs(stdout, stderr, "exiftool metadata")
            if flags:
                console.print(f"[green]✓ exiftool: {len(flags)} flag(s)[/green]")
                self.found_flags.extend(flags)
            self._extract_metadata_info(stdout, "exiftool")

    def run_binwalk(self):
        if not self.tool_status['binwalk']:
            return

        with tempfile.TemporaryDirectory() as temp_dir:
            stdout, stderr, code = self.run_command(
                ['binwalk', '-e', '-C', temp_dir, str(self.file_path)],
                "binwalk",
                save_output=True
            )

            flags = self.search_flags_from_outputs(stdout, stderr, "binwalk mapping")
            if flags:
                console.print(f"[green]✓ binwalk: {len(flags)} flag(s)[/green]")
                self.found_flags.extend(flags)

            saved_path = self._persist_extracted_files(temp_dir, "binwalk")
            if saved_path:
                console.print(f"[dim]Saved extracted files: {saved_path}[/dim]")

            # Light scan first
            extracted_flags = self._scan_extracted_files(temp_dir, "binwalk")
            if extracted_flags:
                console.print(f"[green]✓ binwalk extracted: {len(extracted_flags)} flag(s)[/green]")
                self.found_flags.extend(extracted_flags)

            # ── RECURSIVE: analyze every extracted file with all tools ──
            if self._depth < self._max_depth:
                for root, dirs, files in os.walk(temp_dir):
                    for fname in files:
                        # _analyze_file already skips _TOOL_ARTIFACTS, but
                        # skip here too to avoid even reading the file.
                        if fname.lower() in _TOOL_ARTIFACTS:
                            continue
                        fpath = os.path.join(root, fname)
                        rec_flags, rec_interesting = self._analyze_file(fpath)
                        if rec_flags:
                            console.print(f"[green]✓ recursive ({fname}): {len(rec_flags)} flag(s)[/green]")
                            self.found_flags.extend(rec_flags)
                        if rec_interesting:
                            self.interesting_strings.extend(rec_interesting)

    def run_steghide(self):
        if not self.tool_status['steghide']:
            return

        if self.file_path.suffix.lower() not in ['.jpg', '.jpeg', '.bmp', '.wav', '.au']:
            return

        # Info probe (empty password)
        stdout, stderr, code = self.run_command(
            f'steghide info "{self.file_path}" -p ""',
            "steghide info",
            shell=True,
            save_output=True
        )

        flags = self.search_flags_from_outputs(stdout, stderr, "steghide info")
        if flags:
            console.print(f"[green]✓ steghide: {len(flags)} flag(s)[/green]")
            self.found_flags.extend(flags)

        has_embedded = 'embedded' in stdout.lower() or 'embedded' in stderr.lower()

        # Decide whether to brute-force
        should_brute = has_embedded or self.auto_brute
        if not should_brute:
            return

        wordlist_to_try = self.wordlist
        mode_label = "auto-brute" if self.auto_brute else "wordlist"
        console.print(
            f"[yellow]→ Bruteforcing steghide ({len(wordlist_to_try)} passwords, {mode_label})...[/yellow]"
        )

        with tempfile.TemporaryDirectory() as temp_dir:
            output_file = os.path.join(temp_dir, 'steghide_extracted.bin')
            cracked = False

            with Progress(
                SpinnerColumn(),
                TextColumn("[progress.description]{task.description}"),
                BarColumn(),
                TextColumn("[cyan]{task.completed}/{task.total}"),
                TimeElapsedColumn(),
                console=console,
                transient=True,
            ) as progress:
                task = progress.add_task("steghide brute", total=len(wordlist_to_try))

                for password in wordlist_to_try:
                    progress.update(task, advance=1,
                                    description=f"steghide: {'(empty)' if not password else password[:20]}")
                    extract_cmd = (
                        f'steghide extract -sf "{self.file_path}" '
                        f'-xf "{output_file}" -p "{password}" -f'
                    )
                    stdout_ex, stderr_ex, code_ex = self.run_command(
                        extract_cmd, "", shell=True, silent=True
                    )

                    if code_ex == 0 and os.path.exists(output_file) and os.path.getsize(output_file) > 0:
                        console.print(
                            f"[green]✓ steghide password found: "
                            f"{'(empty)' if not password else password}[/green]"
                        )
                        saved_path = self._persist_extracted_files(temp_dir, "steghide")
                        if saved_path:
                            console.print(f"[dim]Saved extracted files: {saved_path}[/dim]")

                        # Scan extracted content
                        try:
                            with open(output_file, 'rb') as f:
                                content_bytes = f.read()
                            text_content = content_bytes.decode('utf-8', errors='ignore')
                            flags_ex = self.search_flags(text_content, "steghide extracted")
                            if flags_ex:
                                console.print(f"[green]✓ steghide extracted: {len(flags_ex)} flag(s)[/green]")
                                self.found_flags.extend(flags_ex)
                            encoded_flags, interesting = self.find_encoded_flags(text_content, "steghide extracted")
                            if encoded_flags:
                                self.found_flags.extend(encoded_flags)
                            if interesting:
                                self.interesting_strings.extend(interesting)
                        except Exception:
                            pass

                        # ── RECURSIVE: re-analyze extracted file ──
                        rec_flags, rec_interesting = self._analyze_file(output_file)
                        if rec_flags:
                            console.print(f"[green]✓ recursive (steghide output): {len(rec_flags)} flag(s)[/green]")
                            self.found_flags.extend(rec_flags)
                        if rec_interesting:
                            self.interesting_strings.extend(rec_interesting)

                        cracked = True
                        break

            if not cracked:
                console.print("[red]✗ Steghide bruteforce failed — try custom wordlist with -w[/red]")

    def run_outguess(self):
        if not self.tool_status['outguess']:
            return
        if self.file_path.suffix.lower() not in ['.jpg', '.jpeg']:
            return

        # No-password attempt
        with tempfile.TemporaryDirectory() as temp_dir:
            out_file = os.path.join(temp_dir, 'outguess_out.txt')
            stdout, stderr, code = self.run_command(
                ['outguess', '-r', str(self.file_path), out_file],
                "outguess",
                save_output=True
            )

            flags = self.search_flags_from_outputs(stdout, stderr, "outguess output")
            if flags:
                console.print(f"[green]✓ outguess: {len(flags)} flag(s)[/green]")
                self.found_flags.extend(flags)

            if os.path.exists(out_file) and os.path.getsize(out_file) > 0:
                try:
                    with open(out_file, 'rb') as f:
                        content = f.read().decode('utf-8', errors='ignore')
                    flags_f = self.search_flags(content, "outguess extracted")
                    if flags_f:
                        console.print(f"[green]✓ outguess file: {len(flags_f)} flag(s)[/green]")
                        self.found_flags.extend(flags_f)
                    # ── RECURSIVE ──
                    rec_flags, rec_interesting = self._analyze_file(out_file)
                    if rec_flags:
                        self.found_flags.extend(rec_flags)
                    if rec_interesting:
                        self.interesting_strings.extend(rec_interesting)
                except Exception:
                    pass

        # Brute-force outguess if enabled
        if self.auto_brute:
            self._brute_outguess()

    def _brute_outguess(self):
        """Brute-force outguess with the full wordlist (activated via --auto-brute)."""
        console.print(
            f"[yellow]→ Bruteforcing outguess ({len(self.wordlist)} passwords)...[/yellow]"
        )
        with tempfile.TemporaryDirectory() as temp_dir:
            cracked = False

            with Progress(
                SpinnerColumn(),
                TextColumn("[progress.description]{task.description}"),
                BarColumn(),
                TextColumn("[cyan]{task.completed}/{task.total}"),
                TimeElapsedColumn(),
                console=console,
                transient=True,
            ) as progress:
                task = progress.add_task("outguess brute", total=len(self.wordlist))

                for password in self.wordlist:
                    progress.update(task, advance=1,
                                    description=f"outguess: {'(empty)' if not password else password[:20]}")
                    if not password:
                        continue  # already tried no-password above

                    out_file = os.path.join(temp_dir, f'og_{abs(hash(password))}.txt')
                    stdout_og, stderr_og, code_og = self.run_command(
                        ['outguess', '-k', password, '-r', str(self.file_path), out_file],
                        "", silent=True
                    )

                    extracted_ok = (
                        code_og == 0
                        and os.path.exists(out_file)
                        and os.path.getsize(out_file) > 0
                    )
                    if extracted_ok:
                        console.print(f"[green]✓ outguess password found: {password}[/green]")
                        try:
                            with open(out_file, 'rb') as f:
                                content = f.read().decode('utf-8', errors='ignore')
                            flags_og = self.search_flags(content, "outguess brute extracted")
                            if flags_og:
                                console.print(f"[green]✓ outguess brute: {len(flags_og)} flag(s)[/green]")
                                self.found_flags.extend(flags_og)
                            encoded_flags, interesting = self.find_encoded_flags(content, "outguess brute extracted")
                            if encoded_flags:
                                self.found_flags.extend(encoded_flags)
                            if interesting:
                                self.interesting_strings.extend(interesting)
                        except Exception:
                            pass

                        # ── RECURSIVE ──
                        rec_flags, rec_interesting = self._analyze_file(out_file)
                        if rec_flags:
                            self.found_flags.extend(rec_flags)
                        if rec_interesting:
                            self.interesting_strings.extend(rec_interesting)

                        cracked = True
                        break

            if not cracked:
                console.print("[red]✗ Outguess bruteforce failed — try custom wordlist with -w[/red]")

    def run_foremost(self):
        if not self.tool_status['foremost']:
            return

        with tempfile.TemporaryDirectory() as temp_dir:
            stdout, stderr, code = self.run_command(
                ['foremost', '-i', str(self.file_path), '-o', temp_dir],
                "foremost",
                save_output=True
            )

            saved_path = self._persist_extracted_files(temp_dir, "foremost")
            if saved_path:
                console.print(f"[dim]Saved extracted files: {saved_path}[/dim]")

            extracted_flags = self._scan_extracted_files(temp_dir, "foremost")
            if extracted_flags:
                console.print(f"[green]✓ foremost: {len(extracted_flags)} flag(s)[/green]")
                self.found_flags.extend(extracted_flags)

            # ── RECURSIVE: analyze every extracted file with all tools ──
            if self._depth < self._max_depth:
                for root, dirs, files in os.walk(temp_dir):
                    for fname in files:
                        if fname.lower() in _TOOL_ARTIFACTS:
                            continue
                        fpath = os.path.join(root, fname)
                        rec_flags, rec_interesting = self._analyze_file(fpath)
                        if rec_flags:
                            console.print(f"[green]✓ recursive ({fname}): {len(rec_flags)} flag(s)[/green]")
                            self.found_flags.extend(rec_flags)
                        if rec_interesting:
                            self.interesting_strings.extend(rec_interesting)

    def bruteforce_archives(self):
        """Bruteforce password-protected archives."""
        file_ext = self.file_path.suffix.lower()
        if file_ext == '.zip':
            self._bruteforce_zip()

    def _bruteforce_zip(self):
        """Bruteforce ZIP file passwords with zip-bomb protection."""
        try:
            with zipfile.ZipFile(self.file_path, 'r') as zf:
                # ── Zip-bomb guard ──────────────────────────────────────
                # A zip bomb has a tiny compressed size but expands to GBs.
                # We check both the total uncompressed size and the ratio.
                total_compressed   = sum(i.compress_size   for i in zf.infolist())
                total_uncompressed = sum(i.file_size        for i in zf.infolist())
                if total_uncompressed > _ZIP_BOMB_MAX_BYTES:
                    console.print(
                        f"[red]\u26a0 ZIP skipped: uncompressed size "
                        f"({total_uncompressed // (1024*1024)} MB) exceeds "
                        f"{_ZIP_BOMB_MAX_BYTES // (1024*1024)} MB limit (zip bomb?)[/red]"
                    )
                    return
                if total_compressed > 0 and (total_uncompressed / total_compressed) > _ZIP_BOMB_RATIO:
                    console.print(
                        f"[red]\u26a0 ZIP skipped: compression ratio "
                        f"{total_uncompressed // total_compressed}x exceeds "
                        f"{_ZIP_BOMB_RATIO}x limit (zip bomb?)[/red]"
                    )
                    return
                for info in zf.infolist():
                    if info.flag_bits & 0x1:  # Password protected
                        console.print(
                            f"[yellow]→ Bruteforcing ZIP ({len(self.wordlist)} passwords)...[/yellow]"
                        )

                        with Progress(
                            SpinnerColumn(),
                            TextColumn("[progress.description]{task.description}"),
                            BarColumn(),
                            TextColumn("[cyan]{task.completed}/{task.total}"),
                            TimeElapsedColumn(),
                            console=console,
                            transient=True,
                        ) as progress:
                            task = progress.add_task("zip brute", total=len(self.wordlist))
                            cracked = False

                            for password in self.wordlist:
                                progress.update(task, advance=1,
                                                description=f"zip: {'(empty)' if not password else password[:20]}")
                                try:
                                    pwd_bytes = password.encode('utf-8')
                                    with tempfile.TemporaryDirectory() as temp_dir:
                                        zf.extractall(pwd=pwd_bytes, path=temp_dir)
                                    console.print(
                                        f"[green]✓ ZIP password found: {password if password else '(empty)'}[/green]"
                                    )
                                    with tempfile.TemporaryDirectory() as temp_dir:
                                        zf.extractall(pwd=pwd_bytes, path=temp_dir)
                                        extracted_flags = self._scan_extracted_files(temp_dir, "zip")
                                        if extracted_flags:
                                            console.print(f"[green]✓ zip: {len(extracted_flags)} flag(s)[/green]")
                                            self.found_flags.extend(extracted_flags)

                                        # ── RECURSIVE ──
                                        if self._depth < self._max_depth:
                                            for root, dirs, files in os.walk(temp_dir):
                                                for fname in files:
                                                    fpath = os.path.join(root, fname)
                                                    rec_flags, rec_interesting = self._analyze_file(fpath)
                                                    if rec_flags:
                                                        self.found_flags.extend(rec_flags)
                                                    if rec_interesting:
                                                        self.interesting_strings.extend(rec_interesting)
                                    cracked = True
                                    break
                                except (RuntimeError, zipfile.BadZipFile):
                                    continue
                                except Exception:
                                    continue

                        if not cracked:
                            console.print("[red]✗ ZIP bruteforce failed — try custom wordlist with -w[/red]")
                        break
        except zipfile.BadZipFile:
            pass
        except Exception:
            pass

    # ------------------------------------------------------------------
    # Results
    # ------------------------------------------------------------------

    def show_results(self):
        console.print("\n[bold cyan]═══ Results ═══[/bold cyan]")

        # Deduplicate
        seen_flags = set()
        unique_flags = []
        for item in self.found_flags:
            flag_text = item[0] if isinstance(item, tuple) else item
            if flag_text not in seen_flags:
                seen_flags.add(flag_text)
                unique_flags.append(item)

        seen_interesting = set()
        unique_interesting = []
        for item in self.interesting_strings:
            data_text = item[0] if isinstance(item, tuple) else item
            if data_text not in seen_interesting:
                seen_interesting.add(data_text)
                unique_interesting.append(item)

        actionable_tags = (
            "[CTF Keyword]", "[Credentials]", "[Access Info]",
            "[URL]", "[File Path]", "[Code/Command]",
        )
        actionable_interesting = [
            item for item in unique_interesting
            if any(tag in (item[1] if isinstance(item, tuple) else "") for tag in actionable_tags)
        ]

        seen_metadata = set()
        unique_metadata = []
        for item in self.metadata_findings:
            data_text = item[0] if isinstance(item, tuple) else item
            if data_text not in seen_metadata:
                seen_metadata.add(data_text)
                unique_metadata.append(item)

        # Flags
        if unique_flags:
            console.print(f"\n[bold green]🎯 Flags ({len(unique_flags)}):[/bold green]")
            for item in unique_flags:
                flag_text   = item[0] if isinstance(item, tuple) else item
                source_text = item[1] if isinstance(item, tuple) else "unknown"
                console.print(f"  [green]•[/green] {flag_text} [dim]({source_text})[/dim]")
        else:
            console.print("\n[yellow]No flags found[/yellow]")

        # Interesting
        if actionable_interesting:
            console.print(f"\n[bold yellow]🔍 Interesting ({len(actionable_interesting)}):[/bold yellow]")
            for item in actionable_interesting[:5]:
                data_text   = item[0] if isinstance(item, tuple) else item
                source_text = item[1] if isinstance(item, tuple) else "unknown"
                console.print(f"  [yellow]•[/yellow] {data_text[:80]}... [dim]({source_text})[/dim]")
            if len(actionable_interesting) > 5:
                console.print(f"  [dim]... and {len(actionable_interesting) - 5} more[/dim]")

        # Metadata
        if unique_metadata:
            console.print(f"\n[bold magenta]📋 Metadata ({len(unique_metadata)}):[/bold magenta]")
            for item in unique_metadata[:3]:
                field_text  = item[0] if isinstance(item, tuple) else item
                source_text = item[1] if isinstance(item, tuple) else "unknown"
                console.print(f"  [magenta]•[/magenta] {field_text[:80]} [dim]({source_text})[/dim]")
            if len(unique_metadata) > 3:
                console.print(f"  [dim]... and {len(unique_metadata) - 3} more[/dim]")

        # Offer raw output if nothing found
        if not unique_flags:
            if Confirm.ask(
                "\n[yellow]No flags found. Do you want to see raw tool outputs?[/yellow]",
                default=False
            ):
                for tool_name, stdout, stderr in self.tool_outputs:
                    combined = f"{stdout}\n{stderr}".strip()
                    if combined:
                        console.print(f"\n[bold cyan]═══ {tool_name} ═══[/bold cyan]")
                        console.print(combined, highlight=False)

        console.print()

    def run(self):
        if not self.quiet:
            self.show_banner()
            self.show_tool_status()
        self.scan()
        if not self.quiet:
            self.show_results()


# ---------------------------------------------------------------------------
# CLI Entry Point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description='CTFuck - Steganography Automation Tool for CTF',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  ctfuck image.png  -f "FLAG{"
  ctfuck image.jpg  -f "CTF{"  -w /usr/share/wordlists/rockyou.txt
  ctfuck image.jpg  -f "CTF{"  -b
  ctfuck archive.zip -f "flag{"
        """
    )

    parser.add_argument(
        'file',
        help='File to analyze'
    )

    parser.add_argument(
        '-f', '--flag-format',
        help='Ozel flag formati. Eger verilmezse otomatik olarak yaygin 25 format taranir.'
    )

    parser.add_argument(
        '-w', '--wordlist',
        help='Custom wordlist file for bruteforce attacks'
    )

    parser.add_argument(
        '-b', '--auto-brute',
        action='store_true',
        default=False,
        help='Enable auto brute-force for steghide and outguess using the embedded wordlist (or -w)'
    )

    parser.add_argument(
        '-d', '--depth',
        type=int,
        default=3,
        help='Maximum recursion depth for nested file analysis (default: 3)'
    )

    args = parser.parse_args()

    if args.depth < 1:
        args.depth = 1
    elif args.depth > _MAX_RECURSION_DEPTH_HARD_CAP:
        args.depth = _MAX_RECURSION_DEPTH_HARD_CAP

    formats = [args.flag_format] if args.flag_format else DEFAULT_FLAG_FORMATS
    
    # Otomatik modda eger ozel olarak kapatilmadiyse brute force acilir
    enable_brute = True if (not args.flag_format and not args.wordlist) else args.auto_brute
    
    try:
        ctfuck = CTFuck(
            file_path=args.file,
            flag_formats=formats,
            wordlist=args.wordlist,
            auto_brute=enable_brute,
            max_recursion_depth=args.depth,
        )
        ctfuck.run()

    except KeyboardInterrupt:
        console.print("\n[bold red]✗ Interrupted[/bold red]")
        exit(1)
    except Exception as e:
        console.print(f"\n[bold red]✗ Error: {str(e)}[/bold red]")
        exit(1)


if __name__ == '__main__':
    main()
